In [19]:
import numpy as np

X = np.array([[10,20,10],
            [2,5,2],
            [8,17,7],
            [9,20,10],
            [12,22,11]])
X

array([[10, 20, 10],
       [ 2,  5,  2],
       [ 8, 17,  7],
       [ 9, 20, 10],
       [12, 22, 11]])

In [20]:
X = np.mat(X)
meanVals = np.mean(X, axis=0)
A = X - meanVals           # A - zero-,ean (centered) version of X
C = np.cov(A, rowvar=0)    # C - covariance matrix of X

print(C)

[[ 14.2   25.3   13.5 ]
 [ 25.3   46.7   24.75]
 [ 13.5   24.75  13.5 ]]


In [21]:
# C is also (1/(N-1)) A.T*A
print(np.dot(A.T,A)/(np.shape(X)[0]-1))

[[ 14.2   25.3   13.5 ]
 [ 25.3   46.7   24.75]
 [ 13.5   24.75  13.5 ]]


In [22]:
import scipy as sp

In [24]:
# Now we can obtain eigenvalues and eigenvectors of the covariance matrix:
np.set_printoptions(precision=2,suppress=True)
e, ev = np.linalg.eig(C)
print("Eigenvalues")
print(e)
print()
print("Eigenvectors")
print(ev)

Eigenvalues
[ 73.72   0.38   0.3 ]

Eigenvectors
[[ 0.43  0.9  -0.04]
 [ 0.79 -0.41 -0.45]
 [ 0.42 -0.16  0.89]]


In [26]:
# Transform the full data into the new feature space based on the eigenvectors:
newFeatures = ev.T
XTrans = np.dot(newFeatures, A.T)
print(XTrans.T)

[[  4.17   0.     0.26]
 [-14.61   0.17   0.25]
 [ -0.35  -0.1   -0.97]
 [  3.74  -0.9    0.3 ]
 [  7.05   0.83   0.16]]


In [27]:
#  Sort the eigenvectors in the decreasing order of their eigenvalues and take the top k:
reducedFeatures = ev[:,0].T 
reducedXTrans = np.dot(reducedFeatures, A.T)
print(reducedXTrans.T)

[[  4.17]
 [-14.61]
 [ -0.35]
 [  3.74]
 [  7.05]]


In [ ]:
# Could also use Scikitlearn
